### PR TITLE
Fix issue #31

### PR DESCRIPTION
**Pull request by loserdong**

### CODE REVIEW

**Comment by hit9** [comment]
Tested？

**Comment by loserdong** [comment]
yes, i run the mocha cases, and it work well

**Comment by hit9** [comment]
Sorry but this patch breaks tests.

**Comment by loserdong** [comment]
I'm so sorry, I retry the case today, and find there are two case failed.

when the conn destroy, and then there will be wrong value return.

any good idea for the conn close and then reconnect condition?

**Pull request merged**
